title: Fede's Blog
author:
  name: phoryne
  email: N/A

description: >-
  Clear, engaging English articles on computer science, from code to emerging tech.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  # Minima skin selection. Available skins are:
  #   * classic            Default, light color scheme.
  #   * dark               Dark variant of the classic skin.
  #   * auto               Adaptive skin (classic + dark).
  #   * solarized-light    Light solarized color scheme.
  #   * solarized-dark     Dark solarized color scheme.
  #   * solarized          Adaptive solarized scheme.
  skin: dark

  # Navigation
  nav_pages:
    - about.md

  # Show excerpts on homepage
  show_excerpts: false

  # Date format (default: "%b %d, %Y")
  # date_format: "%b-%d-%Y"

  # Social Media Links
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/phoryne"
